# Nome da aplicação
spring.application.name=stock-manager-api

# ============================================================
# CONFIGURAÇÃO DO SQLITE
# ============================================================
# Cria um arquivo "stock.db" na raiz do projeto
spring.datasource.url=jdbc:sqlite:stock.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=admin
spring.datasource.password=admin

# Dialeto Hibernate para SQLite (permite criar tabelas)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# CONFIGURAÇÃO DO JWT (segredo e expiração)
# ============================================================
# Use uma chave de 256 bits (32 caracteres). Esta é apenas para dev.
jwt.secret = 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 horas em milissegundos
jwt.expiration = 86400000 


# ============================================================
# SERVER
# ============================================================
server.port=8080

# ============================================================
# SWAGGER / OPENAPI (Documentação)
# ============================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ============================================================
# ACTUATOR (Health Check e Monitoramento)
# ============================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true